- name: Download Qt6
  hosts: all
  vars:
  tasks:
    - name: Download Qt6 installer for Windows
      win_get_url:
        url: "https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe"
        dest: '{{ ansible_env.USERPROFILE }}\Downloads\qt-installer.exe'
      when: ansible_os_family == 'Windows'
  
    - name: Download Qt6 installer for Linux
      win_get_url:
        url: "https://download.qt.io/official_releases/online_installers/PLACE_YOUR_FILE_HERE"
        dest: '{{ ansible_env.USERPROFILE }}\Downloads\qt-installer.exe'
      when: ansible_os_family == 'Debian'
